<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="PropertyReference.xsl"?>
<!DOCTYPE properties [
<!--  <!ENTITY % DocBookDTD PUBLIC "-//OASIS//DTD DocBook V4.2//EN"
"/usr/share/sgml/docbook_4.2/docbook.dtd">
 %DocBookDTD; -->
 <!ELEMENT properties (property*)>

 <!ELEMENT property (descr, attributes?, optattributes?,
                     seealso?, freestyle?, example? )>
 <!ATTLIST property
   name CDATA #REQUIRED
   id CDATA #REQUIRED
   inheritable (Yes|No) "No" 
   scenario (Yes|No) "No"
 >

 <!ELEMENT descr (para*)>
 <!ELEMENT attributes (attr*)>
 <!ELEMENT attr (para*)>
 <!ATTLIST attr
   name CDATA #REQUIRED
   type CDATA #REQUIRED
   list (0|1) "0"
   optional (0|1) "0"
 >

 <!ELEMENT optattributes (optattr*)>
 <!ELEMENT optattr (#PCDATA)>

 <!ELEMENT seealso (also*)>
 <!ELEMENT also (#PCDATA)>
 <!ELEMENT freestyle (para*)>
 <!ELEMENT example (#PCDATA)>

 <!ELEMENT para (#PCDATA|varname|link|simplelist|screen)*>
 <!ELEMENT varname (#PCDATA)*>
 <!ELEMENT link (#PCDATA)>
 <!ATTLIST link
   linkend CDATA #REQUIRED
 >
 <!ELEMENT simplelist (member)*>
 <!ATTLIST simplelist
   type CDATA #REQUIRED
   columns CDATA #REQUIRED
 >
 <!ELEMENT member (#PCDATA|para|varname|link)*>
 <!ELEMENT screen (#PCDATA)>
 
  <!ENTITY example_depends SYSTEM
   "../../TestSuite/Syntax/Correct/Depends1.tjp">
  <!ENTITY example_extend SYSTEM
   "../../TestSuite/Syntax/Correct/CustomAttributes.tjp">
  <!ENTITY example_limits SYSTEM
   "../../TestSuite/Syntax/Correct/Limits-1.tjp">
  <!ENTITY example_precedes SYSTEM
   "../../TestSuite/Syntax/Correct/Precedes1.tjp">
]>

<properties>
 <property name="The TJP File" id="global_scope">
 <descr><para>All TaskJuggler project files should start with the
project property and must contain at least one task definition. To
visualize the results of the scheduling process, at least one of the
reports should be specified.</para></descr>
 <optattributes>
   <optattr>account</optattr>
   <optattr>copyright</optattr>
   <optattr>csvaccountreport</optattr>
   <optattr>csvresourcereport</optattr>
   <optattr>csvtaskreport</optattr>
   <optattr>export</optattr>
   <optattr>flags_declare</optattr>
   <optattr>htmlaccountreport</optattr>
   <optattr>htmlresourcereport</optattr>
   <optattr>htmlstatusreport</optattr>
   <optattr>htmltaskreport</optattr>
   <optattr>htmlweeklycalendar</optattr>
   <optattr>include</optattr>
   <optattr>macro</optattr>
   <optattr>maxeffort</optattr>
   <optattr>limits</optattr>
   <optattr>priority</optattr>
   <optattr>projectid</optattr>
   <optattr>projectids</optattr>
   <optattr>project</optattr>
   <optattr>rate</optattr>
   <optattr>resource</optattr>
   <optattr>shift</optattr>
   <optattr>supplement</optattr>
   <optattr>task</optattr>
   <optattr>vacation_global</optattr>
   <optattr>xmlreport</optattr>
  </optattributes>
 </property>
 <property name="account" id="account">
  <descr><para>Declares an account. Accounts can be used to calculate costs
of tasks or the whole project. Account declaration may be nested, but
only the top level accounts may have a type attribute specified. An
account that has sub-accounts may not have a <link
linkend="PROPERTY_credit">credit</link> or a <link
linkend="PROPERTY_kotrusid">kotrusid</link>.  sub-accounts inherit
this type.</para></descr>
  <attributes>
   <attr name="id" type="ID">
    <para>Each account must have a unique ID.</para>
   </attr> 
   <attr name="name" type="STRING"/>
   <attr name="type" type="ID" optional="1">
    <para>The type may be <varname>cost</varname> or
<varname>revenue</varname>.</para></attr>
  </attributes>
  <optattributes>
   <optattr>account</optattr>
   <optattr>credit</optattr>
   <optattr>kotrusid</optattr>
  </optattributes>
  <seealso>
   <also>csvaccountreport</also>
   <also>htmlaccountreport</also>
  </seealso>
 </property>
 <property name="account" id="account_task" inheritable="Yes">
  <descr><para>All amounts associated with the task will be credited
to the specified account.</para></descr>
  <attributes>
   <attr name="accountid" type="ID"/>
  </attributes>
  <seealso>
   <also>account</also>
  </seealso>
 </property>
 <property name="accumulate" id="accumulate" inheritable="No">
  <descr><para>If this attribute is specified the values in the calendar
columns are accumulated over the reported interval.</para></descr>
 </property>
 <property name="allowredefinition" id="allowredefinition" inheritable="No">
  <descr><para>If this attribute is specified, redefinitions of task,
resources or accounts are not flagged as errors. The primary use of
this attribute is for projects that are created by merging sub projects
which are again the result of sub project merging. In certain
situations enclosing tasks, accounts or resources can be included in more
than one sub project. This attribute then avoids the error which is
in most other cases a real user error.</para>

<para>In case attributes of the same property must be specified in two
different locations the <link linkend="PROPERTY_supplement">supplement</link>
construct is the recommended way to do this.</para></descr>
 </property>
 <property name="allocate" id="allocate" inheritable="Yes">
  <descr><para>Specify which resources should be allocated to the
task.</para></descr>
  <attributes>
   <attr name="resource" type="ID"/>
  </attributes>
  <optattributes>
   <optattr>alternative</optattr>
   <optattr>load</optattr>
   <optattr>mandatory</optattr>
   <optattr>persistent</optattr>
   <optattr>select</optattr>
   <optattr>shift_selection</optattr>
  </optattributes>
  <seealso>
   <also>effort</also>
  </seealso>
 </property>
 <property name="alternative" id="alternative" inheritable="No">
  <descr><para>A list of alternative resources for an allocation.</para></descr>
  <attributes>
   <attr name="resource" type="ID" list="1"/>
  </attributes>
  <seealso>
   <also>select</also>
  </seealso>
 </property>
 <property name="barlabels" id="barlabels" inheritable="No">
  <descr><para>Specifies the contense of the Gantt chart like bars in
HTML calendar columns. The default is to show load values.</para></descr>
  <attributes>
   <attr name="mode" type="ID">
    <para>See table below for possible values.</para>
   </attr>
  </attributes>
  <seealso>
   <also>columns</also>
   <also>showprojectids</also>
  </seealso>
  <freestyle>
   <para><simplelist type="horiz" columns="2">
   
   <member><varname>empty</varname></member>
   <member>Do not show any values on calendar bars.</member>
   
   <member><varname>load</varname></member>
   <member>Show task or resource load on calendar bars.</member>
   
   </simplelist></para>
  </freestyle>
 </property>
 <property name="booking" id="booking" inheritable="No" scenario="Yes">
  <descr><para></para></descr>
  <attributes>
   <attr name="start" type="DATE"/>
   <attr name="end" type="DATE"/>
   <attr name="task" type="ID"/>
  </attributes>
  <optattributes>
   <optattr>sloppy</optattr>
  </optattributes>
  <seealso>
   <also>projection</also>
  </seealso>
 </property>
 <property name="caption" id="caption" inheritable="No">
  <descr><para>Specifies the caption used for a report table.</para></descr>
  <attributes>
   <attr name="text" type="STRING"/>
  </attributes>
  <seealso>
   <also>complete</also>
   <also>copyright</also>
   <also>headline</also>
  </seealso>
 </property>
 <property name="celltext" id="celltext" inheritable="No">
  <descr><para>Specifies an alternative text that is used for all
cells of the column. Usually such a text contains a runtime macro,
otherwise all cells of the column will have the same fixed value.</para></descr>
  <attributes>
   <attr name="text" type="STRING"/>
  </attributes>
  <seealso>
   <also>cellurl</also>
  </seealso>
 </property>
 <property name="cellurl" id="cellurl" inheritable="No">
  <descr><para>Specifies an URL that is attached to the cell contense
of the cells of the column in HTML reports.</para></descr>
  <attributes>
   <attr name="url" type="STRING"/>
  </attributes>
  <seealso>
   <also>celltext</also>
  </seealso>
 </property>
 <property name="columns" id="columns" inheritable="No">
  <descr><para>Specifies which columns shell be included in a
report.</para>

<para>All columns support macro expansion. Contrary to the normal
macro expansion, these macros are expanded during the report
generation. So the value of the macro is being changed after each
table cell or table line. Consequently only build in macros can be
used. To protect the macro calls agains expansion during the initial
file processing, the report macros must be prefixed with an additional
<varname>$</varname>.</para></descr>
  <attributes>
   <attr name="columnid" type="ID" list="1">
    <para>See table below for possible values.</para>
   </attr>
  </attributes>
  <optattributes>
   <optattr>celltext</optattr>
   <optattr>cellurl</optattr>
   <optattr>hidecelltext</optattr>
   <optattr>hidecellurl</optattr>
   <optattr>subtitle</optattr>
   <optattr>subtitleurl</optattr>
   <optattr>title</optattr>
   <optattr>titleurl</optattr>
  </optattributes>
  <freestyle>
   <para><simplelist type="horiz" columns="2">
   
   <member><varname>completed</varname></member>
   <member>The percentage the task has been completed already. This is
   either the value specified by <link
   linkend="PROPERTY_complete">complete</link> or a value computed according
   to the current date (or the date specified by <link
   linkend="PROPERTY_now">now</link>) and the length, duration or
   effort.</member>
   
   <member><varname>cost</varname></member>
   <member>The accumulated costs of the task and its sub tasks</member>
   
   <member><varname>criticalness</varname></member>
   <member>The criticalness of the task. It is a measure for the
   probability that an effort task gets the requested resources
   early.</member>
   
   <member><varname>cost</varname></member>
   <member>The accumulated costs of the task and its sub tasks</member>
   
   <member><varname>daily</varname></member>
   <member>A day-by-day calendar view of the tasks</member>
   
   <member><varname>depends</varname></member>
   <member>The task index of the tasks on which this task
   depends</member>
   
   <member><varname>duration</varname></member>
   <member>The duration of the task</member>
   
   <member><varname>effort</varname></member>
   <member>The effort put into the task</member>
   
   <member><varname>end</varname></member>
   <member>The end date of a task</member>
   
   <member><varname>endbuffer</varname></member>
   <member>The percentage of the endbuffer</member>
   
   <member><varname>endbufferstart</varname></member>
   <member>The start time of the end buffer</member>
   
   <member><varname>flags</varname></member>
   <member>The list of flags assigned to the task or resource</member>
   
   <member><varname>follows</varname></member>
   <member>The task index of the tasks that depend on this task</member>
   
   <member><varname>freeload</varname></member>
   <member>The workload of the resource that has not been allocated.</member>
   
   <member><varname>hierarchindex</varname></member>
   <member>The hierarchical index of a task. The index is calculated from the
   hierachical structure of the list as well as the start and end dates.
   </member>
   
   <member><varname>hierarchno</varname></member>
   <member>The hierarchical number of a task. It is based on the order of
   declaration.</member>
   
   <member><varname>id</varname></member>
   <member>The global ID of a task</member>
   
   <member><varname>index</varname></member>
   <member>The index of a task. The index is calculated from the
   hierachical structure of the list as well as the start and end dates.
   </member>
   
   <member><varname>kotrusid</varname></member>
   <member>The KotrRUs ID of the resource</member>
   
   <member><varname>maxeffort</varname></member>
   <member>The maximum daily load wanted for the resource</member>
   
   <member><varname>maxend</varname></member>
   <member>The latest desired end date</member>
   
   <member><varname>maxstart</varname></member>
   <member>The latest desired start date</member>
   
   <member><varname>mineffort</varname></member>
   <member>The minimum daily load wanted for the resource</member>
   
   <member><varname>minend</varname></member>
   <member>The earliest desired end date</member>
   
   <member><varname>minstart</varname></member>
   <member>The earliest desired start date</member>
   
   <member><varname>monthly</varname></member>
   <member>A month-by-month calendar view of the tasks</member>
   
   <member><varname>name</varname></member>
   <member>The name of a task, resource, or account</member>
   
   <member><varname>no</varname></member>
   <member>The task index in the list. It starts with 1 and increases for
   every listed item by 1.</member>
   
   <member><varname>note</varname></member>
   <member>The description of the task</member>
   
   <member><varname>pathcriticalness</varname></member>
   <member>The overall criticalness of the task. It is a measure for the
   probability that an effort task gets scheduled as early as
   possible. The tasks of the most critical path have the highest path
   criticalness.</member>
   
   <member><varname>priority</varname></member>
   <member>The scheduling priority</member>
   
   <member><varname>profit</varname></member>
   <member>The accumulated profit of the task and its sub tasks</member>
   
   <member><varname>projectid</varname></member>
   <member>The project ID of the task</member>
   
   <member><varname>projectids</varname></member>
   <member>The project IDs of the projects a resource is allocated to</member>
   
   <member><varname>quarterly</varname></member>
   <member>A quarter-by-quarter calendar view of the tasks</member>
   
   <member><varname>rate</varname></member>
   <member>The daily rate of the resource</member>
   
   <member><varname>reference</varname></member>
   <member>A reference to a URL that contains further information.</member>
   
   <member><varname>resources</varname></member>
   <member>The names of the used resources</member>
   
   <member><varname>responsibilies</varname></member>
   <member>A list of all tasks indicies for which a resource is
   responsible </member>
   
   <member><varname>responsible</varname></member>
   <member>The name of the resource responsible for a task</member>
   
   <member><varname>revenue</varname></member>
   <member>The accumulated revenue of the task and its sub tasks</member>
   
   <member><varname>scenario</varname></member>
   <member>The name of the scenario. This column is helpful when multiple
   scenarios are shown in the table. See also <link
   linkend="PROPERTY_scenarios">scenarios</link>.</member>
   
   <member><varname>seqno</varname></member>
   <member>The task index in the order of declaration. Each
   time a task declaration is completed, the sequence number is increased
   by 1. </member>
   
   <member><varname>schedule</varname></member>
   <member>A detailed schedule of the allocations for the resource.</member>
   
   <member><varname>start</varname></member>
   <member>The start date of a task</member>
   
   <member><varname>startbuffer</varname></member>
   <member>The percentage of the start buffer</member>
   
   <member><varname>startbufferend</varname></member>
   <member>The end time of the start buffer</member>
   
   <member><varname>status</varname></member>
   <member>The current status of the task. This is derived from the
   current date or the date specified by <link
   linkend="PROPERTY_now">now</link> and the degree of completion. The
   degree of completion is either computed or has been specified by <link
   linkend="PROPERTY_complete">complete</link>.</member>
   
   <member><varname>total</varname></member>
   <member>Total accumulated values</member>
   
   <member><varname>utilization</varname></member>
   <member>The ratio between the allocated work load of the resource
   and it's overall available work load.</member>
   
   <member><varname>weekly</varname></member>
   <member>A week-by-week calendar view of the tasks</member>
   
   <member><varname>yearly</varname></member>
   <member>A year-by-year calendar view of the tasks</member>
   
   </simplelist></para>
<para>The following macros are supported for normal table cells:</para>

<para><simplelist type="horiz" columns="2">
<member><varname>$${0}</varname></member>
<member>This is the original value of the table cell. This macro is
useful if the user would like to extend the cell text with a fixed
string.</member>

<member><varname>$${accountid}</varname></member>
<member>The ID of the account.</member>

<member><varname>$${resourceid}</varname></member>
<member>The ID of the resource.</member>

<member><varname>$${taskid}</varname></member> <member>the
id of the task.</member>

</simplelist></para>

<para>Additionally the original contense of other cells of the same
report line can be accessed by the column ID. The following columns
are supported:</para>

<para><varname>index, no, hierachindex, hierachno, id,
name</varname></para>

<para>For the title or sub title of the calendar columns
(<varname>daily, weekly, monthly, quarterly, yearly</varname>) the
following macros are supported:</para>

<para><varname>$${day}, $${month}, $${week}, $${quarter},
$${year}</varname>.</para>
  </freestyle>
 </property>
 <property name="complete" id="complete" inheritable="No"
scenario="Yes">
  <descr><para>Specifies what percentage of the task is already
completed. This can be useful for project tracking. Reports with
calendar elements may show the completed part of the task in a
different color.</para>

<para>Tasks may not have subtasks if this attribute is used.</para></descr>
  <attributes>
   <attr name="percent" type="INTEGER">
    <para>The value must be between 0 and 100.</para>
   </attr>
  </attributes>
 </property>
 <property name="copyright" id="copyright" inheritable="No">
  <descr><para>Adds a copyright notice to all subsequently defined
reports. This notice may contain any text. The notice is added at the
bottom of the report.</para></descr>
  <attributes>
   <attr name="text" type="STRING"/>
  </attributes>
  <seealso>
   <also>booking</also>
   <also>headline</also>
   <also>caption</also>
  </seealso>
 </property>
 <property name="credit" id="credit">
  <descr><para>Credits the specified amount to the account at the
specified date. The description should contain some information about
the reason for the transaction.</para></descr>
  <attributes>
   <attr name="date" type="DATE"/>
   <attr name="description" type="STRING"/>
   <attr name="amount" type="REAL"/>
  </attributes>
 </property>
 <property name="csvaccountreport" id="csvaccountreport">
  <descr><para>The report lists all specified account values as a comma
separated list. This is usefull to export TaskJuggler data to Office
Suites like OpenOffice.org or KOffice.</para></descr>
  <attributes>
   <attr name="filename" type="STRING"/>
  </attributes>
  <optattributes>
   <optattr>accumulate</optattr>
   <optattr>columns</optattr>
   <optattr>end_report</optattr>
   <optattr>rollupaccount</optattr>
   <optattr>hideaccount</optattr>
   <optattr>sortaccounts</optattr>
   <optattr>start_report</optattr>
  </optattributes>
  <seealso>
   <also>htmlaccountreport</also>
  </seealso>
 </property>
 <property name="csvresourcereport" id="csvresourcereport" inheritable="No">
  <descr><para>The report lists all specified resource values as a
comma separated list. This is usefull to export TaskJuggler data to
Office Suites like OpenOffice.org or KOffice.</para></descr>
  <attributes>
   <attr name="filename" type="STRING"/>
  </attributes>
  <optattributes>
   <optattr>accumulate</optattr>
   <optattr>columns</optattr>
   <optattr>end_report</optattr>
   <optattr>rollupresource</optattr>
   <optattr>hideresource</optattr>
   <optattr>sortresources</optattr>
   <optattr>start_report</optattr>
  </optattributes>
  <seealso>
   <also>htmlresourcereport</also>
  </seealso>
 </property>
 <property name="csvtaskreport" id="csvtaskreport" inheritable="No">
  <descr><para>The report lists all specified task values as a comma
separated list. This is usefull to export TaskJuggler data to Office
Suites like OpenOffice.org or KOffice.</para></descr>
  <attributes>
   <attr name="filename" type="STRING"/>
  </attributes>
  <optattributes>
   <optattr>accumulate</optattr>
   <optattr>columns</optattr>
   <optattr>end_report</optattr>
   <optattr>rolluptask</optattr>
   <optattr>hidetask</optattr>
   <optattr>sorttasks</optattr>
   <optattr>start_report</optattr>
  </optattributes>
  <seealso>
   <also>htmltaskreport</also>
  </seealso>
 </property>
 <property name="currency" id="currency" inheritable="No">
  <descr><para>The default currency unit.</para></descr>
  <attributes>
   <attr name="text" type="STRING"/>
  </attributes>
  <seealso>
   <also>currencyformat</also>
  </seealso>
 </property>
 <property name="currencyformat" id="currencyformat" inheritable="Yes">
  <descr><para>These values specify the default format used for all
currency values. The <varname>negativeprefix</varname> and
<varname>negativesuffix</varname> strings enclose negative currency
values. The <varname>thousandseparator</varname> can be used to make
large numbers more readable. The <varname>fractionseparator</varname>
separates the fractional part from the rest.
<varname>fractiondigits</varname> specifies how many fractional digits
should be shown at a maximum.</para></descr>
  <attributes>
   <attr name="negativeprefix" type="STRING"/>
   <attr name="negativesuffix" type="STRING"/>
   <attr name="thousandseparator" type="STRING"/>
   <attr name="fractionseparator" type="STRING"/>
   <attr name="fractiondigits" type="STRING"/>
  </attributes>
  <seealso>
   <also>currency</also>
  </seealso>
 </property>
 <property name="dailymax" id="dailymax" inheritable="Yes">
  <descr><para>Sets the daily limit of a resource usage or a resource
allocation to a task.</para></descr>
  <attributes>
   <attr name="value" type="REAL"/>
   <attr name="unit" type="UNIT"/>
  </attributes>
  <seealso>
   <also>monthlymax</also>
   <also>weeklymax</also>
  </seealso>
 </property>
 <property name="dailyworkinghours" id="dailyworkinghours" inheritable="No">
  <descr><para>Set the average number of working hours per day. This
is used as the base to convert working hours into working days. This
affects for example the <link linkend="PROPERTY_length">length</link> task
attribute. The default value is 8 hours and should work for most
Western countries.  The value you specify should match the settings
you specified for <link
linkend="PROPERTY_workinghours">workinghours</link>.</para></descr>
  <attributes>
   <attr name="hours" type="REAL"/>
  </attributes>
  <seealso>
   <also>yearlyworkingdays</also>
  </seealso>
 </property>
 <property name="depends" id="depends" inheritable="No">
  <descr><para>Specifies that the task cannot start before the task
with the specified IDs have been finished. If multiple IDs are
specified, they must be separated by commas. IDs must be either global
or relative. A relative ID starts with a number of '!'. Each '!' moves
the scope to the parent task. Global IDs do
not contain '!', but have IDs separated by dots.</para>

<para>Each task ID can have optional attribues enclosed in
braces.</para>

<para>By using the 'depends' attribute, the scheduling policy is
automatically set to <varname>asap</varname>. If 'depends' and
'precedes' are used, the last policy counts.</para></descr>
  <attributes>
   <attr name="task" type="ID" list="1"/>
  </attributes>
  <optattributes>
   <optattr>gapduration</optattr>
   <optattr>gaplength</optattr>
  </optattributes>
  <seealso>
   <also>complete</also>
   <also>precedes</also>
  </seealso>
  <example>&example_depends;</example>
 </property>
 <property name="disabled" id="disabled" inheritable="No">
  <descr><para>Disables the scenario for scheduling.</para></descr>
 </property>
 <property name="duration" id="duration" inheritable="No"
 scenario="Yes">
  <descr><para>Specifies the time the task occupies the resources.
This is calender time, not working time. 7d means one week. If
resources are specified they are allocated when available.
Availability of resources has no impact on the duration of the task.
It will always be the specified duration.</para>

<para>Tasks may not have subtasks if this attribute is used.</para></descr>
  <attributes>
   <attr name="value" type="REAL"/>
   <attr name="unit" type="UNIT"/>
  </attributes>
  <seealso>
   <also>effort</also>
   <also>length</also>
  </seealso>
 </property>
 <property name="efficiency" id="efficiency" inheritable="Yes">
  <descr><para>The efficiency of a resource can be used for two
purposes. First you can use it as a crude way to model a team. A team
of 5 people should have an efficiency of 5.0. Keep in mind that you
cannot track the member of the team individually if you use this
feature. The other use is to model performance variations between your
resources.</para>
<para>All resources that do not contribute effort to the task, should
have an efficiency of 0.0.</para></descr>
  <attributes>
   <attr name="value" type="REAL"/>
  </attributes>
  <seealso>
   <also>load</also>
  </seealso>
 </property>
 <property name="effort" id="effort" inheritable="No" scenario="Yes">
  <descr><para>Specifies the effort needed to complete the task. An
effort of 4d can be done with 2 full-time resources in 2 days. The
task will not finish before the resources have contributed the
specified effort. So the duration of the task will depend on the
availability of the resources.</para>

<para>WARNING: In almost all real world projects effort is not the product
of time and resources. This is only true if the task can be
partitioned without adding any overhead. For more information about
this read "The Mythical Man-Month" by Frederick P. Brooks, Jr.</para>

<para>Tasks may not have subtasks if this attribute is
used.</para></descr>
  <attributes>
   <attr name="value" type="REAL"/>
   <attr name="unit" type="UNIT"/>
  </attributes>
  <seealso>
   <also>duration</also>
   <also>length</also>
  </seealso>
 </property>
 <property name="end" id="end_report" inheritable="No">
  <descr><para>Specifies the end date of the report. In task reports only
tasks that start before this end date are listed.</para></descr>
  <attributes>
   <attr name="date" type="DATE"/>
  </attributes>
  <seealso>
   <also>start_report</also>
  </seealso>
 </property>
 <property name="end" id="end_task" inheritable="Yes" scenario="Yes">
  <descr><para>The end date of the task</para></descr>
  <attributes>
   <attr name="date" type="DATE"/>
  </attributes>
  <seealso>
   <also>start_task</also>
   <also>maxend</also>
   <also>minend</also>
   <also>endbuffer</also>
  </seealso>
 </property>
 <property name="endbuffer" id="endbuffer" inheritable="No"
scenario="Yes">
  <descr><para>Specifies how much slack time you expect to have at the
end of the task.</para></descr>
  <attributes>
   <attr name="percent" type="REAL">
    <para>Percent slack of the overall effort, duration or length of
the task.</para>
   </attr>
  </attributes>
  <seealso>
   <also>duration</also>
   <also>effort</also>
   <also>length</also>
  </seealso>
 </property>
 <property name="endcredit" id="endcredit" inheritable="No"
scenario="Yes">
  <descr><para>Specifies an amount that is credited to the account
specified by the <link linkend="PROPERTY_account_task">account</link> property
at the moment the tasks ends.</para></descr>
  <attributes>
   <attr name="amount" type="REAL"/>
  </attributes>
  <seealso>
   <also>startcredit</also>
  </seealso>
 </property>
 <property name="export" id="export" inheritable="No">
  <descr><para>The export report looks like a regular taskjuggler file
but contains fixed start and end dates for all tasks. The tasks only
have start and end times, their description and their project id
listed. No other attributes are exported unless they are requested
using the <link
linkend="PROPERTY_taskattributes">taskattributes</link> attribute. The
contense also depends on the extension of the file name. If the file
name ends with <varname>.tjp</varname> a complete project with header,
resource and shift definitions is generated. In case it ends with
<varname>.tji</varname> only the tasks and resource allocations are
exported.</para>

<para>If specified the resource usage for the tasks is reported as
well. But only those allocations are listed that belong to tasks
listed in the same export report.</para>

<para>The export report can be used to share certain tasks or
milestones with other projects. When an export report is included the
project IDs of the included tasks must be declared first with the
<link linkend="PROPERTY_projectid">project id property</link>.</para></descr>
  <attributes>
   <attr name="filename" type="STRING"/>
  </attributes>
  <optattributes>
   <optattr>hideresource</optattr>
   <optattr>hidetask</optattr>
   <optattr>rollupresource</optattr>
   <optattr>rolluptask</optattr>
   <optattr>scenarios</optattr>
   <optattr>taskattributes</optattr>
   <optattr>taskroot</optattr>
  </optattributes>
  <seealso>
   <also>include</also>
  </seealso>
 </property>
 <property name="extend" id="extend" inheritable="No">
  <descr><para>Often it is desireable to collect more information in
the project file than is necessary for task scheduling and resource
allocation. To add such information to tasks, resources or accounts
the user can extend these properties with user-defined attributes. The
new attributes can be <varname>text</varname> or
<varname>reference</varname> attributes. Optionally the user can
specify if the attribute value should be inherited from the enclosing
property.</para></descr>
  <attributes>
   <attr name="property" type="ID">